### ISSUE TITLE
不能编译

### ISSUE THREAD

**Issue by doudouded** [xiaeroc/xdd#28]
[root@localhost xdd]# go build  
# github.com/Mrs4s/go-cqhttp/internal/btree
/usr/local/go/path/pkg/mod/github.com/xiaeroc/go-cqhttp@v1.0.0-xiaeroc/internal/btree/chunk.go:36:14: undefined: unsafe.Add
/usr/local/go/path/pkg/mod/github.com/xiaeroc/go-cqhttp@v1.0.0-xiaeroc/internal/btree/chunk.go:45:27: undefined: unsafe.Add
/usr/local/go/path/pkg/mod/github.com/xiaeroc/go-cqhttp@v1.0.0-xiaeroc/internal/btree/chunk.go:109:13: undefined: unsafe.Add
/usr/local/go/path/pkg/mod/github.com/xiaeroc/go-cqhttp@v1.0.0-xiaeroc/internal/btree/chunk.go:110:13: undefined: unsafe.Add
/usr/local/go/path/pkg/mod/github.com/xiaeroc/go-cqhttp@v1.0.0-xiaeroc/internal/btree/chunk.go:111:13: undefined: unsafe.Add
/usr/local/go/path/pkg/mod/github.com/xiaeroc/go-cqhttp@v1.0.0-xiaeroc/internal/btree/helper.go:31:11: undefined: unsafe.Add
note: module requires Go 1.17
# github.com/Mrs4s/MiraiGo/topic
/usr/local/go/path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211208080234-25c67a3ee1c1/topic/feed.go:67:43: time.Now().UnixMilli undefined (type time.Time has no field or method UnixMilli)
note: module requires Go 1.17

**Comment by xiaeroc** [comment]
升级go版本

**Comment by xiaeroc** [comment]
建议升级到1.17.4

doudouded ***@***.***> 于2021年12月13日周一 21:39写道：

**Comment by doudouded** [comment]
好的，谢谢大佬，我试下
